smi: "[1CH]1=CC=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL503634.6a" n: 780764 conn: true usmi: "[1cH]1cc[1cH]cc1"
smi: "[1CH]1=CC=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL265174.6a" n: 364992 conn: true usmi: "[1cH]1c[1cH][1cH]cc1"
smi: "[1CH]1=[1CH][1CH]=C[1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL263810.6a" n: 65485 conn: true usmi: "[1cH]1[1cH]c[1cH]c[1cH]1"
smi: "[1CH]1=CC=[1CH]N=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL156037.6a" n: 43831 conn: true usmi: "[n]1[1cH]cc[1cH]c1"
smi: "[1CH]1=C[1CH]=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL539442.6a" n: 22862 conn: true usmi: "[1cH]1[1cH]c[1cH][1cH]c1"
smi: "[1CH]1=N[1CH]=[1CH]C=N1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL527864.6a" n: 16591 conn: true usmi: "c1[n][1cH][n][1cH][1cH]1"
smi: "[1CH]1=[1CH][1CH]=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1082532.6a" n: 12817 conn: true usmi: "[1cH]1[1cH][1cH]cc[1cH]1"
smi: "[1CH]1=C[1CH]=[1CH]N=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL536883.6a" n: 12581 conn: true usmi: "[n]1[1cH][1cH]c[1cH]c1"
smi: "[1CH]1=NC=[1CH]C=N1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1171471.6a" n: 10473 conn: true usmi: "[1cH]1[n]c[1cH]c[n]1"
smi: "[1CH]1=N[1CH]=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL540427.6a" n: 9281 conn: true usmi: "[n]1[1cH][1cH]cc[1cH]1"
smi: "[1CH]1=[1CH]N=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL454492.6a" n: 5697 conn: true usmi: "[1cH]1[n][1cH][1cH][1cH][n]1"
smi: "[1CH]1=NN=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL600052.6a" n: 5439 conn: true usmi: "[n]1[n][1cH]cc[1cH]1"
smi: "[1CH]1=[1CH][1CH]=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL503634.6a" n: 5413 conn: true usmi: "c1[1cH][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH]C=N[1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL601080.6a" n: 4936 conn: true usmi: "[n]1[1cH]c[1cH][1cH]c1"
smi: "[1CH]1=NC=[1CH]N=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL268339.6a" n: 4167 conn: true usmi: "[n]1[1cH]c[n][1cH]c1"
smi: "C1=[1CH]C=C[1NH+]=C1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL505408.6a" n: 3740 conn: true usmi: "[1N+]1=CC=[1CH]C=C1"
smi: "[1CH]1=N[1CH]=[1CH][CH2:70]N1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL540488.6a" n: 3384 conn: true exo: "[70O]" usmi: "O=c1[nH][1cH][n][1cH][1cH]1"
smi: "[1CH]1=NC=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL6512.6a" n: 3335 conn: true usmi: "c1[n][1cH][1cH][n][1cH]1"
smi: "[1CH]1=[1CH]C=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL1085225.6a" n: 2874 conn: true usmi: "[n]1[1cH]c[1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH][1CH]=[1CH][1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL1200455.6a" n: 2870 conn: true usmi: "[1cH]1[1cH][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH][1CH]=[1CH][1CH]=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL507464.6a" n: 1846 conn: true usmi: "[n]1[1cH][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=CC(=O)[1NH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3309471.6a" n: 1615 conn: true usmi: "O=c1[1nH]cc[1cH]c1"
smi: "[1CH]1=[1CH]C=N[1NH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL530151.6a" n: 1610 conn: true usmi: "O=c1[1nH][n]c[1cH][1cH]1"
smi: "[1NH]1C(=O)[1NH]C(=O)[1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL505033.6a" n: 1536 conn: true usmi: "O=c1[1nH]c(=O)[1nH][1cH][1cH]1"
smi: "[1CH]1=[1CH]C(=O)N[1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL3347310.6a" n: 1409 conn: true usmi: "O=c1[nH][1cH]c[1cH][1cH]1"
smi: "C1=C[1NH]C(=O)N=[1CH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D3]:[ax2r6](=[A]):[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL610191.6a" n: 1244 conn: true usmi: "O=c1[1nH]cc[1cH][n]1"
smi: "[1CH]1=[1CH]N=[1CH][1CH]=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL501701.6a" n: 1244 conn: true usmi: "[n]1[1cH][1cH][n][1cH][1cH]1"
smi: "[1CH]1=CC(=O)[1NH][1CH]=N1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL4116118.6a" n: 1043 conn: true usmi: "O=c1[1nH][1cH][n][1cH]c1"
smi: "[1CH]1=C[1CH]=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL39016.6a" n: 1043 conn: true usmi: "[n]1[1cH][1cH]c[1cH][1cH]1"
smi: "[CH2:70]1N[1CH]=CC=[1CH]1" smt: "[ax2r6]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL48776.6a" n: 955 conn: true exo: "[70O]" usmi: "O=c1[nH][1cH]cc[1cH]1"
smi: "[1CH]1=[1CH]N=N[1CH]=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL4543253.6a" n: 935 conn: true usmi: "[n]1[1cH][n][n][1cH][1cH]1"
smi: "[1CH]1=[1CH][1CH]=[1CH]C=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3310403.6a" n: 901 conn: true usmi: "[n]1c[1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=C[1CH]=NN=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL6582.6a" n: 852 conn: true usmi: "c1[1cH][1cH][n][n][1cH]1"
smi: "C1=[1CH][1NH]C(=O)[1NH]C1=O" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL4303787.6a" n: 831 conn: true usmi: "O=c1c[1cH][1nH]c(=O)[1nH]1"
smi: "[1CH]1=[1CH]C=[1CH]O[CH2:70]1" smt: "[ax2r6D>2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL7333.6a" n: 804 conn: true exo: "[70O]" usmi: "O=c1o[1cH]c[1cH][1cH]1"
smi: "[1CH]1=CN=[1CH]NC1=O" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL14909.6a" n: 751 conn: true usmi: "O=c1[nH][1cH][n]c[1cH]1"
smi: "[1CH]1=C[1NH]C(=O)C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL3309965.6a" n: 687 conn: true usmi: "O=c1[1nH]c[1cH][1cH]c1"
smi: "[1NH]1C(=O)[1CH]=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3](=[A]):[ax2r6]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL4434769.6a" n: 665 conn: true usmi: "O=c1[1nH][1cH][n][1cH][1cH]1"
smi: "[1NH+]1=[1CH]C=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL1184569.6a" n: 603 conn: true usmi: "[1N+]1=[1CH]C=[1CH]C=[1CH]1"
smi: "[1CH]1=[1CH]C(=O)N[1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL3347280.6a" n: 591 conn: true usmi: "O=c1[nH][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH]C=C[1NH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL4434794.6a" n: 555 conn: true usmi: "O=c1[1nH]cc[1cH][1cH]1"
smi: "[1NH]1C(=O)N=[1CH][1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL11752.6a" n: 534 conn: true usmi: "O=c1[1nH]c[1cH][1cH][n]1"
smi: "C1(=O)[1CH]=[1CH]C=[1CH][1NH]1" smt: "[ax2r6]1(=[A]):[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL22333.6a" n: 523 conn: true usmi: "O=c1[1nH][1cH]c[1cH][1cH]1"
smi: "[1CH]1=[1CH]NC(=O)[1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL8178.6a" n: 503 conn: true usmi: "O=c1[nH][1cH][1cH]c[1cH]1"
smi: "[CH2:70]1[1NH][CH2:71]C=[1CH]N1" smt: "[ax2r6]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL4543258.6a" n: 491 conn: true exo: "[70O].[71O]" usmi: "O=c1[1nH]c(=O)c[1cH][nH]1"
smi: "[1CH]1=N[1NH]C(=O)C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL529058.6a" n: 467 conn: true usmi: "O=c1[1nH][n][1cH][1cH]c1"
smi: "[1CH]1=[1CH]O[1CH]=CC1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL14592.6a" n: 416 conn: true usmi: "O=c1c[1cH]o[1cH][1cH]1"
smi: "[1NH]1[1CH]=NC=[1CH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6]:1=[A]" id: "CHEMBL10867.6a" n: 386 conn: true usmi: "O=c1[1nH][1cH][n]c[1cH]1"
smi: "[1NH]1C(=O)C=[1CH]N=C1" smt: "[ax2r6D3]1:[ax2r6](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL32404.6a" n: 377 conn: true usmi: "O=c1[1nH]c[n][1cH]c1"
smi: "[1CH]1=CC=[1CH][1NH][CH2:70]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL11157.6a" n: 351 conn: true exo: "[70O]" usmi: "O=c1[1nH][1cH]cc[1cH]1"
smi: "[1NH]1N=C[1CH]=CC1=O" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL4436840.6a" n: 341 conn: true usmi: "O=c1[1nH][n]c[1cH]c1"
smi: "[1CH]1=[1CH][1CH]=NN=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL6805.6a" n: 335 conn: true usmi: "[n]1[n][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=NN=[1CH]NC1=O" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL31107.6a" n: 317 conn: true usmi: "O=c1[nH][1cH][n][n][1cH]1"
smi: "[1NH]1[CH2:70][1CH]=N[1CH]=[1CH]1" smt: "[ax2r6D>2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:1" id: "CHEMBL50698.6a" n: 286 conn: true exo: "[70O]" usmi: "O=c1[1nH][1cH][1cH][n][1cH]1"
smi: "[1NH]1C(=O)N=[1CH][1NH]C1=O" smt: "[ax2r6D3]1:[ax2r6](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6]:1=[A]" id: "CHEMBL459142.6a" n: 240 conn: true usmi: "O=c1[n][1cH][1nH]c(=O)[1nH]1"
smi: "N1=[1CH][1NH]C=[1CH]C1=O" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL10440.6a" n: 225 conn: true usmi: "O=c1[n][1cH][1nH]c[1cH]1"
smi: "[1CH]1=C[1CH]=[1CH][1NH]C1=O" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL8444.6a" n: 223 conn: true usmi: "O=c1[1nH][1cH][1cH]c[1cH]1"
smi: "[1NH]1C(=O)[1CH]=NC=[1CH]1" smt: "[ax2r6D3]1:[ax2r6](=[A]):[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL18759.6a" n: 208 conn: true usmi: "O=c1[1nH][1cH]c[n][1cH]1"
smi: "[1CH]1=[1CH]C(=O)[1CH]=C[1NH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6](=[A]):[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL4552407.6a" n: 186 conn: true usmi: "O=c1[1cH]c[1nH][1cH][1cH]1"
smi: "[1NH]1[1CH]=[1CH][1CH]=[1CH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL3323275.6a" n: 183 conn: true usmi: "O=c1[1nH][1cH][1cH][1cH][1cH]1"
smi: "[1NH+]1=C[1CH]=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL18432.6a" n: 153 conn: true usmi: "[1N+]1=C[1CH]=[1CH]C=C1"
smi: "[1CH]1=NN=[1CH][1NH]C1=O" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL456890.6a" n: 152 conn: true usmi: "O=c1[1nH][1cH][n][n][1cH]1"
smi: "N1=[1CH][1NH][1CH]=[1CH]C1=O" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL10759.6a" n: 147 conn: true usmi: "O=c1[n][1cH][1nH][1cH][1cH]1"
smi: "[1CH]1=[N:70]C=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL57680.6a" n: 143 conn: true exo: "[70O]" usmi: "O=[n]1[1cH]cc[1cH]c1"
smi: "[1NH]1[CH2:70]N[1CH]=[1CH][CH2:71]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL34149.6a" n: 134 conn: true exo: "[70O].[71O]" usmi: "O=c1[1nH]c(=O)[nH][1cH][1cH]1"
smi: "[1CH]1=[1CH]N[1CH]=[1CH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL444503.6a" n: 131 conn: true usmi: "O=c1[1cH][1cH][nH][1cH][1cH]1"
smi: "[1CH]1=C[1NH]C(=O)[1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL1185871.6a" n: 118 conn: true usmi: "O=c1[1nH]c[1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH][CH2:70]O[1CH]=[1CH]1" smt: "[ax2r6D>2]1:[ax2r6D>2]:[ax2r6]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:1" id: "CHEMBL50396.6a" n: 117 conn: true exo: "[70O]" usmi: "O=c1o[1cH][1cH][1cH][1cH]1"
smi: "C1=C[1NH][CH2:70][CH2:71][1NH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL95650.6a" n: 104 conn: true exo: "[70O].[71O]" usmi: "O=c1c(=O)[1nH]cc[1nH]1"
smi: "[1NH+]1=CC=[1CH][1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL4116087.6a" n: 99 conn: true usmi: "[1N+]1=CC=[1CH][1CH]=C1"
smi: "[CH2:70]1[1NH][CH2:71][1NH][1CH]=[1CH]1" smt: "[ax2r6]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:1" id: "CHEMBL4441893.6a" n: 92 conn: true exo: "[70O].[71S]" usmi: "S=c1[1nH]c(=O)[1cH][1cH][1nH]1"
smi: "[1NH]1C(=O)N=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL4439806.6a" n: 82 conn: true usmi: "O=c1[1nH][1cH]c[1cH][n]1"
smi: "N1=[1CH]C(=O)N[1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL69014.6a" n: 68 conn: true usmi: "O=c1[nH][1cH][1cH][n][1cH]1"
smi: "[CH2:70]1[1NH][1CH]=[1CH][1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D>2]:1" id: "CHEMBL1564177.6a" n: 67 conn: true exo: "[70S]" usmi: "S=c1[1nH][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=CC=[1CH][1NH+]=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL45248.6a" n: 59 conn: true usmi: "[1N+]1=C[1CH]=CC=[1CH]1"
smi: "[1CH]1=[1CH]N=C[1NH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6]:1=[A]" id: "CHEMBL143996.6a" n: 57 conn: true usmi: "O=c1[1nH]c[n][1cH][1cH]1"
smi: "C1=C[1NH+]=[1CH][1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL4543457.6a" n: 53 conn: true usmi: "[1N+]1=[1CH][1CH]=[1CH]C=C1"
smi: "[1CH]1=CC=[1NH+][1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL45381.6a" n: 50 conn: true usmi: "[1N+]1=CC=[1CH]C=[1CH]1"
smi: "N1=[1CH]N=N[1CH]=N1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL17447.6a" n: 47 conn: true usmi: "[n]1[n][1cH][n][n][1cH]1"
smi: "[1CH]1=[1CH]C=[1CH]NC1=N" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL570855.6a" n: 44 conn: true usmi: "N=c1[nH][1cH]c[1cH][1cH]1"
smi: "[1NH+]1=[1CH]C=C[1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL45459.6a" n: 43 conn: true usmi: "[1N+]1=[1CH]C=C[1CH]=C1"
smi: "[N:70]1=[1CH][1CH]=CC=[1CH]1" smt: "[ax2r6]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL65949.6a" n: 43 conn: true exo: "[70O]" usmi: "O=[n]1[1cH][1cH]cc[1cH]1"
smi: "[1CH]1=NN[1CH]=NC1=O" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL4525249.6a" n: 43 conn: true usmi: "O=c1[n][1cH][nH][n][1cH]1"
smi: "N1=[1CH]C=N[1CH]=N1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL351412.6a" n: 42 conn: true usmi: "c1[n][1cH][n][n][1cH]1"
smi: "[CH2:70]1[1CH]=[1CH][1CH]=[1CH]N1" smt: "[ax2r6]1:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL225896.6a" n: 38 conn: true exo: "[70S]" usmi: "S=c1[nH][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=C[1CH]=[1CH]O[CH2:70]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL37810.6a" n: 36 conn: true exo: "[70O]" usmi: "O=c1o[1cH][1cH]c[1cH]1"
smi: "[1CH]1=CC(=O)[1NH][1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL1795905.6a" n: 36 conn: true usmi: "O=c1[1nH][1cH][1cH][1cH]c1"
smi: "[1NH+]1=[1CH]N=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL107051.6a" n: 36 conn: true usmi: "[1N+]1=[1CH]N=[1CH]C=[1CH]1"
smi: "[1CH]1=CC=[1CH][CH2:70]O1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3310190.6a" n: 35 conn: true exo: "[70O]" usmi: "O=c1o[1cH]cc[1cH]1"
smi: "S1[CH2:70][1NH][CH2:71]C=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL1869630.6a" n: 34 conn: true exo: "[70N].[71O]" usmi: "O=c1[1nH]c(=N)s[1cH]c1"
smi: "[1NH+]1=[1CH][1CH]=[1CH][1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL135356.6a" n: 29 conn: true usmi: "[1N+]1=[1CH][1CH]=[1CH][1CH]=[1CH]1"
smi: "[1CH]1=[1CH]C=[1NH+]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL56520.6a" n: 26 conn: true usmi: "[1N+]1=C[1CH]=[1CH][1CH]=C1"
smi: "[1CH]1=C[1NH+]=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL3306594.6a" n: 26 conn: true usmi: "[1N+]1=[1CH]N=[1CH][1CH]=C1"
smi: "[1CH]1=[1CH][CH2:70][1NH][1CH]=C1" smt: "[ax2r6D>2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL1350696.6a" n: 23 conn: true exo: "[70S]" usmi: "S=c1[1nH][1cH]c[1cH][1cH]1"
smi: "N1[1CH]=N[1CH]=[1CH][CH2:70]1" smt: "[ax2r6D2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6]:1" id: "CHEMBL160005.6a" n: 22 conn: true exo: "[70S]" usmi: "S=c1[nH][1cH][n][1cH][1cH]1"
smi: "[1CH]1=C[1CH]=N[1NH+]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL81934.6a" n: 22 conn: true usmi: "[1N+]1=[1CH][1CH]=C[1CH]=N1"
smi: "N1[1CH]=C[1CH]=[1CH]C1=S" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6]:1=[A]" id: "CHEMBL4469728.6a" n: 21 conn: true usmi: "S=c1[nH][1cH]c[1cH][1cH]1"
smi: "[1CH]1=NC=[1CH]N[CH2:70]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL6647.6a" n: 20 conn: true exo: "[70O]" usmi: "O=c1[nH][1cH]c[n][1cH]1"
smi: "[1NH+]1=[1CH]C=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL44733.6a" n: 20 conn: true usmi: "[1N+]1=[1CH]C=[1CH]C=C1"
smi: "[N:70]1=C[1CH]=[1CH]C=[1CH]1" smt: "[ax2r6]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL68199.6a" n: 19 conn: true exo: "[70O]" usmi: "O=[n]1[1cH]c[1cH][1cH]c1"
smi: "N1=[1CH]NC=[1CH]C1=O" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6]:1=[A]" id: "CHEMBL69178.6a" n: 18 conn: true usmi: "O=c1[n][1cH][nH]c[1cH]1"
smi: "[1CH]1=[1CH][1NH][1CH]=[1CH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL29016.6a" n: 18 conn: true usmi: "O=c1[1cH][1cH][1nH][1cH][1cH]1"
smi: "[N:70]1=[1CH][1CH]=[1CH]C=[1CH]1" smt: "[ax2r6]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL66985.6a" n: 16 conn: true exo: "[70O]" usmi: "O=[n]1[1cH]c[1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH][CH2:70]N[1NH][CH2:71]1" smt: "[ax2r6D>2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL1348034.6a" n: 15 conn: true exo: "[70O].[71O]" usmi: "O=c1[nH][1nH]c(=O)[1cH][1cH]1"
smi: "[1NH]1N=C[1CH]=NC1=O" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL4888852.6a" n: 13 conn: true usmi: "O=c1[1nH][n]c[1cH][n]1"
smi: "N1[CH2:70][1CH]=C[1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:1" id: "CHEMBL124557.6a" n: 13 conn: true exo: "[70S]" usmi: "S=c1[nH][1cH][1cH]c[1cH]1"
smi: "[1CH]1=CC=[1CH]N=[1NH+]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL82844.6a" n: 12 conn: true usmi: "[1N+]1=N[1CH]=CC=[1CH]1"
smi: "N1=[1CH][1NH+]=C[1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL340759.6a" n: 12 conn: true usmi: "[1N+]1=C[1CH]=[1CH]N=[1CH]1"
smi: "[1CH]1=[1CH]C=[1CH]N=[1NH+]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL81081.6a" n: 12 conn: true usmi: "[1N+]1=N[1CH]=C[1CH]=[1CH]1"
smi: "[1NH+]1=CN=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL34717.6a" n: 11 conn: true usmi: "[1N+]1=CN=[1CH]C=C1"
smi: "[1NH+]1=[1CH]C=C[1CH]=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL81992.6a" n: 11 conn: true usmi: "[1N+]1=[1CH]C=C[1CH]=N1"
smi: "[1CH]1=N[CH2:70][1NH][CH2:71]N1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL4757743.6a" n: 11 conn: true exo: "[70O].[71O]" usmi: "O=c1[1nH]c(=O)[nH][1cH][n]1"
smi: "[N:70]1=[1CH][1CH]=[N:71][1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6]:1" id: "CHEMBL1312273.6a" n: 11 conn: true exo: "[70O].[71O]" usmi: "O=[n]1[1cH][1cH][n](=O)[1cH][1cH]1"
smi: "[1CH]1=[1NH+]C=C[1CH]=N1" smt: "[ax2r6D3]1:[ax2r6]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL3559543.6a" n: 10 conn: true usmi: "[1N+]1=[1CH]N=[1CH]C=C1"
smi: "[1CH]1=N[1CH]=NC(=O)[1NH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3](=[A]):[ax2r6D3]:1" id: "CHEMBL4788581.6a" n: 10 conn: true usmi: "O=c1[1nH][1cH][n][1cH][n]1"
smi: "[1NH+]1=C[1CH]=[1CH][1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL79671.6a" n: 10 conn: true usmi: "[1N+]1=C[1CH]=[1CH][1CH]=[1CH]1"
smi: "[1NH+]1=[1CH]C=[1CH][1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL149757.6a" n: 10 conn: true usmi: "[1N+]1=[1CH]C=[1CH][1CH]=[1CH]1"
smi: "[1NH+]1=CC=[1CH]C(=O)N1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D2]:1" id: "CHEMBL3392193.6a" n: 9 conn: true usmi: "O=C1N[1N+]=CC=[1CH]1"
smi: "O1[CH2:70][1CH]=[1CH]N=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL1337568.6a" n: 9 conn: true exo: "[70O]" usmi: "O=c1o[1cH][n][1cH][1cH]1"
smi: "[CH2:70]1[1NH][CH2:71]C=[1CH]N1" smt: "[ax2r6]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL295078.6a" n: 9 conn: true exo: "[70S].[71O]" usmi: "S=c1[1nH]c(=O)c[1cH][nH]1"
smi: "[N:70]1=C[1CH]=C[1CH]=[1CH]1" smt: "[ax2r6]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL284852.6a" n: 7 conn: true exo: "[70O]" usmi: "O=[n]1[1cH][1cH]c[1cH]c1"
smi: "S=C1[1NH][1CH]=[1CH]C=[1CH]1" smt: "[A]=[ax2r6]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL1966563.6a" n: 7 conn: true usmi: "S=c1[1nH][1cH][1cH]c[1cH]1"
smi: "[CH2:70]1N[1CH]=N[CH2:71][1NH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL3923335.6a" n: 7 conn: true exo: "[70N].[71O]" usmi: "O=c1[1nH]c(=N)[nH][1cH][n]1"
smi: "[1NH+]1=[1CH][1CH]=C[1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL43784.6a" n: 7 conn: true usmi: "[1N+]1=[1CH][1CH]=C[1CH]=C1"
smi: "[1NH+]1=CC=[1NH+]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1879149.6a" n: 6 conn: true usmi: "[1N+]1=CC=[1N+]C=C1"
smi: "[N:70]1=[1CH]C=N[1CH]=C1" smt: "[ax2r6]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL19190.6a" n: 6 conn: true exo: "[70O]" usmi: "O=[n]1[1cH]c[n][1cH]c1"
smi: "[1CH]1=C[1NH][1CH]=NC1=N" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL527367.6a" n: 6 conn: true usmi: "N=c1[n][1cH][1nH]c[1cH]1"
smi: "S=C1[1NH]C=N[1CH]=[1CH]1" smt: "[A]=[ax2r6]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL1981758.6a" n: 6 conn: true usmi: "S=c1[1nH]c[n][1cH][1cH]1"
smi: "[1NH+]1=[1CH]C=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL906.6a" n: 6 conn: true usmi: "[1N+]1=[1CH]C=[1CH]N=[1CH]1"
smi: "[1CH]1=N[1NH+]=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL83952.6a" n: 6 conn: true usmi: "[1N+]1=[1CH]C=[1CH][1CH]=N1"
smi: "[1NH]1[CH2:70]N[1CH]=[1CH][CH2:71]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL45960.6a" n: 6 conn: true exo: "[70S].[71O]" usmi: "S=c1[1nH]c(=O)[1cH][1cH][nH]1"
smi: "[1NH]1C(=S)N=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL116819.6a" n: 5 conn: true usmi: "S=c1[1nH]cc[1cH][n]1"
smi: "N1(=N[1CH]=CC=[1CH]1)=O" smt: "[ax2r6]1(:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:1)=[A]" id: "CHEMBL98961.6a" n: 5 conn: true usmi: "O=[n]1[n][1cH]cc[1cH]1"
smi: "[1CH]1=NC(=O)[1CH]=N[1NH]1" smt: "[ax2r6D3]1:[ax2r6]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL62167.6a" n: 5 conn: true usmi: "O=c1[n][1cH][1nH][n][1cH]1"
smi: "[1CH]1=[1CH][1CH]=[1CH]C=N1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL229839.6a" n: 5 conn: true usmi: "O=[n]1c[1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH]NC(=N)[1NH]C1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL3899500.6a" n: 5 conn: true usmi: "O=c1[1nH]c(=N)[nH][1cH][1cH]1"
smi: "[1CH]1=NC=[1CH]C(=N)N1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D2]:1" id: "CHEMBL4445985.6a" n: 4 conn: true usmi: "N=c1[nH][1cH][n]c[1cH]1"
smi: "[1CH]1=[1CH][CH2:70]O[1CH]=N1" smt: "[ax2r6D>2]1:[ax2r6D>2]:[ax2r6]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL161184.6a" n: 4 conn: true exo: "[70N]" usmi: "N=c1o[1cH][n][1cH][1cH]1"
smi: "[1CH]1=N[1CH]=CC(=S)[1NH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3](=[A]):[ax2r6D3]:1" id: "CHEMBL3929547.6a" n: 4 conn: true usmi: "S=c1[1nH][1cH][n][1cH]c1"
smi: "[CH2:70]1[1NH][CH2:71]C=[1CH][1NH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:1" id: "CHEMBL1901687.6a" n: 4 conn: true exo: "[70S].[71O]" usmi: "S=c1[1nH][1cH]cc(=O)[1nH]1"
smi: "[1NH+]1=[1CH]C=[1CH][1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL188750.6a" n: 4 conn: true usmi: "[1N+]1=[1CH]C=[1CH][1CH]=C1"
smi: "[1NH+]1=[1CH][1CH]=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL76206.6a" n: 4 conn: true usmi: "[1N+]1=[1CH][1CH]=[1CH]C=[1CH]1"
smi: "[1NH+]1=[1CH]C=[1CH]C=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL83337.6a" n: 3 conn: true usmi: "[1N+]1=[1CH]C=[1CH]C=N1"
smi: "[N:70]1=C[1CH]=NN=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL1457335.6a" n: 3 conn: true exo: "[70O]" usmi: "O=[n]1c[1cH][n][n][1cH]1"
smi: "[1NH+]1=C[1CH]=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL4075341.6a" n: 3 conn: true usmi: "[1N+]1=C[1CH]=[1CH]C=[1CH]1"
smi: "S=C1[1NH]C(=S)N=[1CH][1NH]1" smt: "[A]=[ax2r6]1:[ax2r6D3]:[ax2r6](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL3194157.6a" n: 3 conn: true usmi: "S=c1[n][1cH][1nH]c(=S)[1nH]1"
smi: "[1CH]1=CC=[1CH][CH2:70]N1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL560081.6a" n: 2 conn: true exo: "[70S]" usmi: "S=c1[nH][1cH]cc[1cH]1"
smi: "S1[CH2:70][1CH]=NN=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL2009397.6a" n: 2 conn: true exo: "[70N]" usmi: "N=c1s[1cH][n][n][1cH]1"
smi: "[1CH]1=CC=[1CH][CH2:70][1NH]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL1723652.6a" n: 2 conn: true exo: "[70S]" usmi: "S=c1[1nH][1cH]cc[1cH]1"
smi: "[1CH]1=[1CH]C=[1CH]OC1=S" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1=[A]" id: "CHEMBL106925.6a" n: 2 conn: true usmi: "S=c1o[1cH]c[1cH][1cH]1"
smi: "[1NH+]1=CN=[1CH]C=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL1375521.6a" n: 2 conn: true usmi: "[1N+]1=CN=[1CH]C=[1CH]1"
smi: "[1NH+]1=[1CH]C=N[1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL1504530.6a" n: 2 conn: true usmi: "[1N+]1=[1CH]C=N[1CH]=C1"
smi: "C1(=N)[1NH][1CH]=C[1CH]=N1" smt: "[ax2r6]1(=[A]):[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL139707.6a" n: 2 conn: true usmi: "N=c1[1nH][1cH]c[1cH][n]1"
smi: "[1NH]1C=N[1CH]=[1CH]C1=N" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL503948.6a" n: 2 conn: true usmi: "N=c1[1nH]c[n][1cH][1cH]1"
smi: "[1CH]1=N[1CH]=[1CH][CH2:70]S1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL2007840.6a" n: 2 conn: true exo: "[70N]" usmi: "N=c1s[1cH][n][1cH][1cH]1"
smi: "[1CH]1=C[CH2:70][1NH]N[CH2:71]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1888558.6a" n: 2 conn: true exo: "[70O].[71O]" usmi: "O=c1[nH][1nH]c(=O)c[1cH]1"
smi: "[1CH]1=[1CH]N(=O)=C[1CH]=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL317300.6a" n: 2 conn: true usmi: "O=[n]1c[1cH][n][1cH][1cH]1"
smi: "[1NH+]1=CC=[1CH][1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL588907.6a" n: 2 conn: true usmi: "[1N+]1=CC=[1CH][1CH]=[1CH]1"
smi: "[1CH]1=N[1NH+]=C[1CH]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL1982546.6a" n: 2 conn: true usmi: "[1N+]1=C[1CH]=[1CH][1CH]=N1"
smi: "[1NH+]1=[1CH]N=[1CH]N=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL309713.6a" n: 2 conn: true usmi: "[1N+]1=[1CH]N=[1CH]N=[1CH]1"
smi: "[1CH]1=CC=[1CH][1NH+]=[1CH]1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL1429672.6a" n: 2 conn: true usmi: "[1N+]1=[1CH][1CH]=CC=[1CH]1"
smi: "[1CH]1=[1CH][1CH]=N[1NH]C1=N" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL578382.6a" n: 2 conn: true usmi: "N=c1[1nH][n][1cH][1cH][1cH]1"
smi: "[1NH]1C(=N)[1CH]=[1CH]NC1=O" smt: "[ax2r6D3]1:[ax2r6D3](=[A]):[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6]:1=[A]" id: "CHEMBL1309039.6a" n: 2 conn: true usmi: "O=c1[1nH]c(=N)[1cH][1cH][nH]1"
smi: "[1CH]1=[1CH][1NH+]=[1CH][1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL1378122.6a" n: 2 conn: true usmi: "[1N+]1=[1CH][1CH]=C[1CH]=[1CH]1"
smi: "[O+]1=[1CH][1CH]=[1CH][1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL1967384.6a" n: 2 conn: true usmi: "[o+]1[1cH][1cH][1cH][1cH][1cH]1"
smi: "[1CH]1=[1CH]N(=[1CH][1CH]=[1CH]1)=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3](:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1)=[A]" id: "CHEMBL1088851.6a" n: 2 conn: true usmi: "O=[n]1[1cH][1cH][1cH][1cH][1cH]1"
smi: "[1NH+]1=NC=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL135259.6a" n: 1 conn: true usmi: "[1N+]1=NC=[1CH]C=C1"
smi: "O1[CH2:70][1CH]=[1CH]C=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL1308627.6a" n: 1 conn: true exo: "[70N]" usmi: "N=c1o[1cH]c[1cH][1cH]1"
smi: "[1CH]1=[1CH]C=[1CH]S[CH2:70]1" smt: "[ax2r6D>2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL416591.6a" n: 1 conn: true exo: "[70N]" usmi: "N=c1s[1cH]c[1cH][1cH]1"
smi: "O1[CH2:70][1NH][CH2:71]C=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:1" id: "CHEMBL1989648.6a" n: 1 conn: true exo: "[70O].[71O]" usmi: "O=c1o[1cH]cc(=O)[1nH]1"
smi: "[1CH]1=[1CH]C=C[1NH]C1=S" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL2348270.6a" n: 1 conn: true usmi: "S=c1[1nH]cc[1cH][1cH]1"
smi: "[1NH+]1=[1CH]C=[1CH]N=C1" smt: "[ax2r6D3]1:[ax2r6]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3559565.6a" n: 1 conn: true usmi: "[1N+]1=[1CH]C=[1CH]N=C1"
smi: "[1CH]1=[1CH]C=[1CH]C(=C)C1=C" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3](=[A]):[ax2r6D3]:1=[A]" id: "CHEMBL4575411.6a" n: 1 conn: true usmi: "C=c1[1cH][1cH]c[1cH]c1=C"
smi: "[1CH]1=[1CH]C=N[1NH]C1=N" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL460867.6a" n: 1 conn: true usmi: "N=c1[1nH][n]c[1cH][1cH]1"
smi: "S1[1CH]=N[1CH]=[1CH][CH2:70]1" smt: "[ax2r6D2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6]:1" id: "CHEMBL1973289.6a" n: 1 conn: true exo: "[70S]" usmi: "S=c1s[1cH][n][1cH][1cH]1"
smi: "[1CH]1=[1CH]N(=[1CH]N=C1)=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3](:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1)=[A]" id: "CHEMBL560013.6a" n: 1 conn: true usmi: "O=[n]1[1cH][n]c[1cH][1cH]1"
smi: "[1CH]1=[1CH]N=C[1CH]=N1=O" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1=[A]" id: "CHEMBL327505.6a" n: 1 conn: true usmi: "O=[n]1[1cH]c[n][1cH][1cH]1"
smi: "[N:70]1=N[1CH]=[1CH]C=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:1" id: "CHEMBL1986917.6a" n: 1 conn: true exo: "[70O]" usmi: "O=[n]1[n][1cH][1cH]c[1cH]1"
smi: "[1NH]1[CH2:70][1CH]=[1CH]O[CH2:71]1" smt: "[ax2r6D>2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL369749.6a" n: 1 conn: true exo: "[70O].[71O]" usmi: "O=c1[1nH]c(=O)o[1cH][1cH]1"
smi: "[CH2:70]1[1NH][CH2:71][1NH][1CH]=C1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL1354137.6a" n: 1 conn: true exo: "[70O].[71N]" usmi: "O=c1c[1cH][1nH]c(=N)[1nH]1"
smi: "C1=[1CH]C=[1NH+][1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL4649014.6a" n: 1 conn: true usmi: "[1N+]1=C[1CH]=C[1CH]=[1CH]1"
smi: "[1CH]1=[1CH]N=[1CH][1NH+]=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL3527332.6a" n: 1 conn: true usmi: "[1N+]1=N[1CH]=[1CH]N=[1CH]1"
smi: "[1CH]1=[1CH][1NH+]=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D3]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3545289.6a" n: 1 conn: true usmi: "[1N+]1=[1CH]C=C[1CH]=[1CH]1"
smi: "[1CH]1=[1CH][N:70]=[1CH]N=N1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1632539.6a" n: 1 conn: true exo: "[70O]" usmi: "O=[n]1[1cH][1cH][n][n][1cH]1"
smi: "[1CH]1=[1CH][N:70]=[1CH][1CH]=C1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL3110063.6a" n: 1 conn: true exo: "[70O]" usmi: "O=[n]1[1cH][1cH]c[1cH][1cH]1"
smi: "[CH2:70]1[CH2:71][1NH][CH2:72][CH2:73][1NH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL518746.6a" n: 1 conn: true exo: "[70C].[71O].[72C].[73O]" usmi: "O=c1[1nH]c(=C)c(=O)[1nH]c1=C"
smi: "[CH2:70]1[1NH][1CH]=N[1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D>2]:1" id: "CHEMBL2004456.6a" n: 1 conn: true exo: "[70S]" usmi: "S=c1[1nH][1cH][n][1cH][1cH]1"
smi: "[CH2:70]1[1CH]=[1CH]N[1NH][CH2:71]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL1980342.6a" n: 1 conn: true exo: "[70O].[71O]" usmi: "O=c1c(=O)[1nH][nH][1cH][1cH]1"
smi: "[N:70]1=[1CH][1CH]=N[1CH]=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D3]:[ax2r6D2]:[ax2r6D3]:[ax2r6D3]:1" id: "CHEMBL2130558.6a" n: 1 conn: true exo: "[70O]" usmi: "O=[n]1[1cH][1cH][n][1cH][1cH]1"
smi: "[1CH]1=[1CH][N:70]=C[1CH]=[N:71]1" smt: "[ax2r6D3]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL1490486.6a" n: 1 conn: true exo: "[70O].[71O]" usmi: "O=[n]1[1cH]c[n](=O)[1cH][1cH]1"
smi: "[1NH]1[1NH][CH2:70][1CH]=[1CH][CH2:71]1" smt: "[ax2r6D>2]1:[ax2r6D>2]:[ax2r6]:[ax2r6D>2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL2104566.6a" n: 1 conn: true exo: "[70O].[71O]" usmi: "O=c1[1nH][1nH]c(=O)[1cH][1cH]1"
smi: "[CH2:70]1[1NH][1NH][CH2:71][CH2:72][1NH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:1" id: "CHEMBL3184413.6a" n: 1 conn: true exo: "[70O].[71O].[72O]" usmi: "O=c1[1nH]c(=O)c(=O)[1nH][1nH]1"
