cc_library(
    name = "cmdline_v2",
    srcs = [
        "cmdline.cc",
    ],
    hdrs = [
        "cmdline_v2.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//Foundational/iwaray",
        "//Foundational/iwmisc",
        "//Foundational/iwstring",
    ],
)
