
#define NUMBER_OF_ATOM_TYPE 25
#define UNDEFINED_TRIPOS_ATOM_TYPE 99
#define ATOM_TYPE_H    0
#define ATOM_TYPE_C3   1
#define ATOM_TYPE_C2   2
#define ATOM_TYPE_CAR  3
#define ATOM_TYPE_C1   4
#define ATOM_TYPE_N4   5
#define ATOM_TYPE_N3   6
#define ATOM_TYPE_N2   7
#define ATOM_TYPE_N1   8
#define ATOM_TYPE_NAR  9
#define ATOM_TYPE_NPL3 10
#define ATOM_TYPE_NAM  11
#define ATOM_TYPE_O3   12
#define ATOM_TYPE_O2   13
#define ATOM_TYPE_S3   14
#define ATOM_TYPE_S2   15
#define ATOM_TYPE_P3   16
#define ATOM_TYPE_BR   17
#define ATOM_TYPE_CL   18
#define ATOM_TYPE_F    19
#define ATOM_TYPE_I    20
#define ATOM_TYPE_SO   21
#define ATOM_TYPE_SO2  22
#define ATOM_TYPE_OCO2 23
#define ATOM_TYPE_CCAT 24
#define OUT_OF_RANGE 100
