cc_library(
    name = "iwhistogram",
    srcs = [
        "histogram_fp.cc",
        "iwhistogram.cc",
    ],
    hdrs = [
        "iwhistogram.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//Foundational/iwbits",
        "//Foundational/iwstring",
    ],
)
