filegroup(
    name = "charge_assigner_data",
    srcs = glob(["queries/charges/**"]),
    visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "donor_acceptor_data",
    srcs = glob(["queries/hbonds/**"]),
    visibility = [
        "//visibility:public",
    ],
)
