# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ollection.proto\x12\x18MolecularPropertyProfile\"/\n\x0f\x46loatValueCount\x12\r\n\x05value\x18\x01 \x01(\x02\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"-\n\rIntValueCount\x12\r\n\x05value\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"+\n\x08Quantile\x12\x10\n\x08quantile\x18\x01 \x01(\x02\x12\r\n\x05value\x18\x02 \x01(\x02\"p\n\x0b\x44\x65scription\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nplot_title\x18\x03 \x01(\t\x12\x12\n\nline_color\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\"\xc5\x02\n\nDescriptor\x12:\n\x0b\x64\x65scription\x18\x01 \x01(\x0b\x32%.MolecularPropertyProfile.Description\x12\t\n\x01n\x18\x03 \x01(\x05\x12\x0e\n\x06minval\x18\x04 \x01(\x02\x12\x0e\n\x06maxval\x18\x05 \x01(\x02\x12\x0c\n\x04mean\x18\x06 \x01(\x02\x12\x0e\n\x06median\x18\x07 \x01(\x02\x12\x34\n\x08quantile\x18\x08 \x03(\x0b\x32\".MolecularPropertyProfile.Quantile\x12;\n\nint_values\x18\t \x03(\x0b\x32\'.MolecularPropertyProfile.IntValueCount\x12?\n\x0c\x66loat_values\x18\n \x03(\x0b\x32).MolecularPropertyProfile.FloatValueCount\"\xd4\x01\n\x0c\x44\x65scriptions\x12`\n\x16\x66\x65\x61ture_to_description\x18\x01 \x03(\x0b\x32@.MolecularPropertyProfile.Descriptions.FeatureToDescriptionEntry\x1a\x62\n\x19\x46\x65\x61tureToDescriptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.MolecularPropertyProfile.Description:\x02\x38\x01\x62\x06proto3')



_FLOATVALUECOUNT = DESCRIPTOR.message_types_by_name['FloatValueCount']
_INTVALUECOUNT = DESCRIPTOR.message_types_by_name['IntValueCount']
_QUANTILE = DESCRIPTOR.message_types_by_name['Quantile']
_DESCRIPTION = DESCRIPTOR.message_types_by_name['Description']
_DESCRIPTOR = DESCRIPTOR.message_types_by_name['Descriptor']
_DESCRIPTIONS = DESCRIPTOR.message_types_by_name['Descriptions']
_DESCRIPTIONS_FEATURETODESCRIPTIONENTRY = _DESCRIPTIONS.nested_types_by_name['FeatureToDescriptionEntry']
FloatValueCount = _reflection.GeneratedProtocolMessageType('FloatValueCount', (_message.Message,), {
  'DESCRIPTOR' : _FLOATVALUECOUNT,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.FloatValueCount)
  })
_sym_db.RegisterMessage(FloatValueCount)

IntValueCount = _reflection.GeneratedProtocolMessageType('IntValueCount', (_message.Message,), {
  'DESCRIPTOR' : _INTVALUECOUNT,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.IntValueCount)
  })
_sym_db.RegisterMessage(IntValueCount)

Quantile = _reflection.GeneratedProtocolMessageType('Quantile', (_message.Message,), {
  'DESCRIPTOR' : _QUANTILE,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Quantile)
  })
_sym_db.RegisterMessage(Quantile)

Description = _reflection.GeneratedProtocolMessageType('Description', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTION,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Description)
  })
_sym_db.RegisterMessage(Description)

Descriptor = _reflection.GeneratedProtocolMessageType('Descriptor', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIPTOR,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Descriptor)
  })
_sym_db.RegisterMessage(Descriptor)

Descriptions = _reflection.GeneratedProtocolMessageType('Descriptions', (_message.Message,), {

  'FeatureToDescriptionEntry' : _reflection.GeneratedProtocolMessageType('FeatureToDescriptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _DESCRIPTIONS_FEATURETODESCRIPTIONENTRY,
    '__module__' : 'collection_pb2'
    # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Descriptions.FeatureToDescriptionEntry)
    })
  ,
  'DESCRIPTOR' : _DESCRIPTIONS,
  '__module__' : 'collection_pb2'
  # @@protoc_insertion_point(class_scope:MolecularPropertyProfile.Descriptions)
  })
_sym_db.RegisterMessage(Descriptions)
_sym_db.RegisterMessage(Descriptions.FeatureToDescriptionEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DESCRIPTIONS_FEATURETODESCRIPTIONENTRY._options = None
  _DESCRIPTIONS_FEATURETODESCRIPTIONENTRY._serialized_options = b'8\001'
  _FLOATVALUECOUNT._serialized_start=46
  _FLOATVALUECOUNT._serialized_end=93
  _INTVALUECOUNT._serialized_start=95
  _INTVALUECOUNT._serialized_end=140
  _QUANTILE._serialized_start=142
  _QUANTILE._serialized_end=185
  _DESCRIPTION._serialized_start=187
  _DESCRIPTION._serialized_end=299
  _DESCRIPTOR._serialized_start=302
  _DESCRIPTOR._serialized_end=627
  _DESCRIPTIONS._serialized_start=630
  _DESCRIPTIONS._serialized_end=842
  _DESCRIPTIONS_FEATURETODESCRIPTIONENTRY._serialized_start=744
  _DESCRIPTIONS_FEATURETODESCRIPTIONENTRY._serialized_end=842
# @@protoc_insertion_point(module_scope)
