smi: "[1CH]1=CC=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL503634.6a" n: 780764 conn: true usmi: "[1cH]1cc[1cH]cc1" 
smi: "[1CH]1=CC=[1CH]N=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL156037.6a" n: 43831 conn: true usmi: "[n]1[1cH]cc[1cH]c1" 
smi: "C1=NC=CN=C1" smt: "[ax2r6]1:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:1" id: "CHEMBL268339.6a" n: 20810 conn: false usmi: "[n]1cc[n]cc1" 
smi: "[1CH]1=NC=[1CH]C=N1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1171471.6a" n: 10473 conn: true usmi: "[1cH]1[n]c[1cH]c[n]1" 
smi: "C1=NN=CC=C1" smt: "[ax2r6]1:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:1" id: "CHEMBL600052.6a" n: 8628 conn: false usmi: "c1cc[n][n]c1" 
smi: "C1=[1CH]C=C[1NH+]=C1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL505408.6a" n: 3740 conn: true usmi: "[1N+]1=CC=[1CH]C=C1" 
smi: "[CH2:70]1N[1CH]=CC=[1CH]1" smt: "[ax2r6]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL48776.6a" n: 955 conn: true exo: "[70O]" usmi: "O=c1[nH][1cH]cc[1cH]1" 
smi: "[1CH]1=CO[1CH]=C[CH2:70]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:1" id: "CHEMBL9792.6a" n: 664 conn: true exo: "[70O]" usmi: "O=c1[1cH]co[1cH]c1" 
smi: "[CH2:70]1[1NH][CH2:71]C=[1CH]N1" smt: "[ax2r6]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL4543258.6a" n: 491 conn: true exo: "[70O].[71O]" usmi: "O=c1[1nH]c(=O)c[1cH][nH]1" 
smi: "[1CH]1=C[CH2:70][1CH]=CN1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL4466751.6a" n: 231 conn: true exo: "[70O]" usmi: "O=c1[1cH]c[nH][1cH]c1" 
smi: "C1=C[1NH][CH2:70][CH2:71][1NH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL95650.6a" n: 104 conn: true exo: "[70O].[71O]" usmi: "O=c1c(=O)[1nH]cc[1nH]1" 
smi: "[NH+]1=CN=CC=C1" smt: "[ax2r6]1:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:1" id: "CHEMBL34717.6a" n: 90 conn: false usmi: "N1=CC=C[N+]=C1" 
smi: "N1=CN=NC=N1" smt: "[ax2r6]1:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:1" id: "CHEMBL17447.6a" n: 51 conn: false usmi: "[n]1[n]c[n][n]c1" 
smi: "N1=[1CH]C=N[1CH]=N1" smt: "[ax2r6D2]1:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:1" id: "CHEMBL351412.6a" n: 42 conn: true usmi: "c1[n][1cH][n][n][1cH]1" 
smi: "[1CH]1=CC=[1CH][CH2:70]O1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3310190.6a" n: 35 conn: true exo: "[70O]" usmi: "O=c1o[1cH]cc[1cH]1" 
smi: "S1[CH2:70][1NH][CH2:71]C=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL1869630.6a" n: 34 conn: true exo: "[70N].[71O]" usmi: "O=c1[1nH]c(=N)s[1cH]c1" 
smi: "N1=[1CH]N=C[1NH][CH2:70]1" smt: "[ax2r6D2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL38261.6a" n: 28 conn: true exo: "[70O]" usmi: "O=c1[1nH]c[n][1cH][n]1" 
smi: "[1CH]1=NC=[1CH]N[CH2:70]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL6647.6a" n: 20 conn: true exo: "[70O]" usmi: "O=c1[nH][1cH]c[n][1cH]1" 
smi: "[1CH]1=N[CH2:70][1NH][CH2:71]N1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL4757743.6a" n: 11 conn: true exo: "[70O].[71O]" usmi: "O=c1[1nH]c(=O)[nH][1cH][n]1" 
smi: "[CH2:70]1[1NH][CH2:71]C=[1CH]N1" smt: "[ax2r6]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL295078.6a" n: 9 conn: true exo: "[70S].[71O]" usmi: "S=c1[1nH]c(=O)c[1cH][nH]1" 
smi: "[CH2:70]1N[1CH]=N[CH2:71][1NH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL3923335.6a" n: 7 conn: true exo: "[70N].[71O]" usmi: "O=c1[1nH]c(=N)[nH][1cH][n]1" 
smi: "[CH2:70]1[1NH]C=CC=N1" smt: "[ax2r6D2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:1" id: "CHEMBL342888.6a" n: 6 conn: true exo: "[70N]" usmi: "N=c1[1nH]ccc[n]1" 
smi: "[NH+]1=CC=[NH+]C=C1" smt: "[ax2r6]1:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:[ax2r6]:1" id: "CHEMBL1879149.6a" n: 6 conn: false usmi: "[N+]1=CC=[N+]C=C1" 
smi: "[1NH]1[CH2:70]C=[1CH]C=C1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1485767.6a" n: 3 conn: true exo: "[70N]" usmi: "N=c1[1nH]cc[1cH]c1" 
smi: "C1=[1CH][CH2:70]C=[1CH]O1" smt: "[ax2r6D2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL496910.6a" n: 2 conn: true exo: "[70S]" usmi: "S=c1[1cH]co[1cH]c1" 
smi: "[1CH]1=C[CH2:70][1NH]C=C1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3326430.6a" n: 2 conn: true exo: "[70S]" usmi: "S=c1[1nH]cc[1cH]c1" 
smi: "S1[1CH]=N[CH2:70][1CH]=C1" smt: "[ax2r6D2]1:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL2006972.6a" n: 2 conn: true exo: "[70O]" usmi: "O=c1[n][1cH]sc[1cH]1" 
smi: "[1CH]1=CC=[1CH][CH2:70]N1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL560081.6a" n: 2 conn: true exo: "[70S]" usmi: "S=c1[nH][1cH]cc[1cH]1" 
smi: "S1[CH2:70][1CH]=NN=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL2009397.6a" n: 2 conn: true exo: "[70N]" usmi: "N=c1s[1cH][n][n][1cH]1" 
smi: "[1CH]1=C[CH2:70][1NH]N[CH2:71]1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL1888558.6a" n: 2 conn: true exo: "[70O].[71O]" usmi: "O=c1[nH][1nH]c(=O)c[1cH]1" 
smi: "[1CH]1=N[CH2:70]C=CN1" smt: "[ax2r6D>2]1:[ax2r6D2]:[ax2r6D2]:[ax2r6]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL4579021.6a" n: 1 conn: true exo: "[70N]" usmi: "N=c1[n][1cH][nH]cc1" 
smi: "[CH2:70]1NC=N[1CH]=C1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL1705253.6a" n: 1 conn: true exo: "[70S]" usmi: "S=c1[nH]c[n][1cH]c1" 
smi: "[1NH+]1=NC=[1CH]C=C1" smt: "[ax2r6D3]1:[ax2r6D2]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL135259.6a" n: 1 conn: true usmi: "[1N+]1=NC=[1CH]C=C1" 
smi: "O1[CH2:70][1NH][CH2:71]C=[1CH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:1" id: "CHEMBL1989648.6a" n: 1 conn: true exo: "[70O].[71O]" usmi: "O=c1o[1cH]cc(=O)[1nH]1" 
smi: "[1NH+]1=[1CH]C=[1CH]N=C1" smt: "[ax2r6D3]1:[ax2r6]:[ax2r6D2]:[ax2r6D3]:[ax2r6D2]:[ax2r6D2]:1" id: "CHEMBL3559565.6a" n: 1 conn: true usmi: "[1N+]1=[1CH]C=[1CH]N=C1" 
smi: "[CH2:70]1N[1CH]=C[CH2:71]N1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6]:1" id: "CHEMBL1420427.6a" n: 1 conn: true exo: "[70S].[71S]" usmi: "S=c1c[1cH][nH]c(=S)[nH]1" 
smi: "[CH2:70]1[1NH][CH2:71][1NH][1CH]=C1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:1" id: "CHEMBL1354137.6a" n: 1 conn: true exo: "[70O].[71N]" usmi: "O=c1c[1cH][1nH]c(=N)[1nH]1" 
smi: "[CH2:70]1[CH2:71][1NH][CH2:72][CH2:73][1NH]1" smt: "[ax2r6D2]1:[ax2r6D2]:[ax2r6D>2]:[ax2r6D2]:[ax2r6D2]:[ax2r6D>2]:1" id: "CHEMBL518746.6a" n: 1 conn: true exo: "[70C].[71O].[72C].[73O]" usmi: "O=c1[1nH]c(=C)c(=O)[1nH]c1=C" 
smi: "[CH2:70]1[1NH][1NH][CH2:71][CH2:72][1NH]1" smt: "[ax2r6D2]1:[ax2r6]:[ax2r6D>2]:[ax2r6D2]:[ax2r6]:[ax2r6D>2]:1" id: "CHEMBL3184413.6a" n: 1 conn: true exo: "[70O].[71O].[72O]" usmi: "O=c1[1nH]c(=O)c(=O)[1nH][1nH]1" 
