#!/bin/bash

# when building a pybind environment, we need to copy the shared libraries generated
# by bazel to somewhere permanent.
# Ideally we could install the pre-requisites separately and link against them,
# but in practice this proved too hard. Minor version inconsistencies introduced
# compatibility problems. Using the shared libraries generated by bazel ensures
# that things are compatible.

if [[ -z $1 ]] ; then
  destdir='/lrlhps/users/rx87690/LillyMolPrivate/lib64'
else
  destdir=$1
fi

if [[ ! -d ${destdir} ]] ; then
  mkdir -p ${destdir}
fi

declare -a libs=(
bazel-bin/pybind/lillymol.so
bazel-bin/pybind/lillymol_io.so
bazel-bin/pybind/lillymol_query.so
bazel-bin/pybind/lillymol_reaction.so
bazel-bin/pybind/lillymol_standardise.so
bazel-bin/pybind/lillymol_tools.so
bazel-bin/pybind/lillymol_tsubstructure.so
bazel-bin/Molecule_Lib/*.so
)

for lib in "${libs[@]}" ; do
  if compgen -G "${lib}" > /dev/null; then
    echo "Copying ${lib}"
    cp -f ${lib} ${destdir}
  else
    echo "${lib} not found"
  fi
done
